### ISSUE TITLE
REST API fails execution because an import can not be found

### ISSUE THREAD

**Issue by cmbTea** [1c3t3a/Covid-19-analysis#38]

**Comment by 1c3t3a** [comment]
Please provide further information (system, environment and which package failed)

**Comment by MartinK-SI** [comment]
It's on a freshly installed Windows and reproducable to work with the modification. But needs to be double checked on a Mac

**Comment by MartinK-SI** [comment]
On the Mac it still shows a problem. Needs further investigations
