### ISSUE TITLE
Modify interface to be compatible with different datasources

### ISSUE THREAD

**Issue by 1c3t3a** [1c3t3a/Covid-19-analysis#77]
Currently we're using the [ECDC] (https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwid) data. It would be nice to have an interface which adds a level of abstraction to "plug-in" different datasources such as local data sources as listed in the Excel file [here](https://www.ecdc.europa.eu/en/publications-data/sources-eueea-and-uk-regional-data-covid-19).

**Comment by cmbTea** [comment]
Done in version 5
