### ISSUE TITLE
Add support for arcgis maps

### ISSUE THREAD

**Issue by 1c3t3a** [1c3t3a/Covid-19-analysis#82]
Currently the heat map is generated with [pygal](http://www.pygal.org/en/stable/). The [arcgis](https://www.arcgis.com/index.html) map supports a higher level of detail and generally seems better concerning handling and design. They also provide a Python API [here](https://developers.arcgis.com/python/).

**Comment by cmbTea** [comment]
The Folium maps also support the arches maps and many more maps
